### ISSUE TITLE
Plugins fail to install with a SyntaxError

### ISSUE THREAD

**Issue by the-r3dacted** [wont-stream/shelter-addons#1]
![image](https://github.com/user-attachments/assets/fdb951a0-92f7-4000-9799-1f1faa1930c6)

**Comment by wont-stream** [comment]
Yeah, I’ve noticed that SpikeHD‘s plugin browser has the same issue, it still grabs the GitHub pages subdomain as my username instead of the organization name, I have no idea on how to fix this so for now, if you copy the plugin url just change the sub domain

https://mentally-germ4n.github.io/shelter-plugins/noNitroUpsell

**Comment by wont-stream** [comment]
Assuming you don’t mind I’d like to keep this open until I  can fix this.

**Comment by wont-stream** [comment]
I believe this has been fixed now, would you mind checking it out to make sure it’s not just my end?

**Comment by the-r3dacted** [comment]
I meant to try that URL earlier but forgot

Adding from the website works, thanks.
